### ISSUE TITLE
PLUGIN_APPEND error

### ISSUE THREAD

**Issue by yikelu** [jondkinney/UAD-Hide-And-Seek-Script#17]
Got this error running on Mac.
Had already run Console, VST, VST (mono) successfully. Fails on VST3 and AU.

```
uad-hide-and-seek.rb:328:in `plug_case_statement': uninitialized constant PLUGIN_APPEND (NameError)
Did you mean?  PLUGIN_EXT
	from uad-hide-and-seek.rb:345:in `block in <main>'
	from uad-hide-and-seek.rb:344:in `each'
	from uad-hide-and-seek.rb:344:in `<main>'
```

**Comment by yikelu** [comment]
Fixed it. Patch here:

```
diff --git a/uad-hide-and-seek.rb b/uad-hide-and-seek.rb
index 0fae2eb..89ee32e 100644
--- a/uad-hide-and-seek.rb
+++ b/uad-hide-and-seek.rb
@@ -107,6 +107,7 @@ when /5/ # VST3 Plugins
   PARENT_PATH = '/Library/Audio'
   PLUGIN_DIR = 'Plug-Ins/VST3/Universal Audio'
   PLUGIN_EXT = 'vst3'
+  PLUGIN_APPEND = ''
   UNUSED_PLUGIN_DIR = 'Plugins Unused/VST3/Universal Audio'
   SKIP_PLUGINS = %(
     UAD Antares Auto-Tune Realtime.vst3
@@ -119,6 +120,7 @@ when /6/ # Audio Units
   PARENT_PATH = '/Library/Audio'
   PLUGIN_DIR = 'Plug-Ins/Components'
   PLUGIN_EXT = 'component'
+  PLUGIN_APPEND = ''
   UNUSED_PLUGIN_DIR = 'Plugins Unused/Components'
   SKIP_PLUGINS = []
   REMAINING_FILE_LIST = %(
```

**Comment by jondkinney** [comment]
Huh...well look at that, I was just missing constants! Oops! Thanks for the report and patch. Since you didn't send a PR, I just pushed it straight to the main branch. https://github.com/jondkinney/UAD-Hide-And-Seek-Script/commit/59398e0f0efe49586a2a6367b5eecd9f5bcceb17

**Comment by yikelu** [comment]
Yup, all good. Didn't feel the need to fork/PR a trivial 2 line change.
